import {
  faBuildingColumns,
  faWallet,
  faTrain,
  faHandHoldingDollar,
  faPhone,
  faBook,
  faCapsules,
  faUserDoctor,
  faPiggyBank,
  faPlaneDeparture,
  faPersonRifle,
  faGamepad,
  faShirt,
  faCar,
  faFileInvoiceDollar,
  faBowlFood,
  faUtensils,
  faHouseUser,
  faHouse,
} from "@fortawesome/free-solid-svg-icons";

export const iconsFortawesome = {
  "bank account": faBuildingColumns,
  wallet: faWallet,
  transport: faTrain,
  credit: faHandHoldingDollar,
  phone: faPhone,
  education: faBook,
  medicines: faCapsules,
  "med insurance": faUserDoctor,
  "saving money": faPiggyBank,
  travel: faPlaneDeparture,
  UAF: faPersonRifle,
  enjoyment: faGamepad,
  shopping: faShirt,
  auto: faCar,
  taxs: faFileInvoiceDollar,
  food: faBowlFood,
  "food outside": faUtensils,
  "public utilities": faHouseUser,
  "housing rent": faHouse,
};
